// Assemble a complete clash (mihomo) config from a produced proxy YAML list.
//
// Mirrors Tower's clash export structure: two-tier proxy-groups with no
// circular references.  The top-level "节点选择" only references other
// groups (auto, manual, direct, region…), never raw nodes.  Actual nodes
// live inside "手动切换" and "自动选择".  "🎯 直连" contains only DIRECT.

import { safeLoad } from "@/utils/yaml";

// ── helpers ──────────────────────────────────────────────────────────

function extractNodeNames(proxyYaml) {
    try {
        const doc = safeLoad(proxyYaml);
        if (doc && Array.isArray(doc.proxies)) {
            return doc.proxies
                .map((p) => p && typeof p.name === "string" ? p.name : null)
                .filter(Boolean);
        }
    } catch (_e) { /* fall through */ }
    const names = [];
    const re = /(?:^|\n)\s*-\s*name\s*:\s*["']?([^"'\n]+?)["']?\s*(?:\n|$)/g;
    let m;
    while ((m = re.exec(proxyYaml))) {
        names.push(m[1].trim());
    }
    return names;
}

function q(s) { return '"' + s + '"'; }

function selectGroup(name, members, opts) {
    const lines = [];
    lines.push("  - name: " + q(name));
    lines.push("    type: select");
    if (opts && opts.hidden) lines.push("    hidden: true");
    lines.push("    proxies:");
    for (const m of members) lines.push("      - " + q(m));
    return lines.join("\n");
}

function urlTestGroup(name, url, interval, tolerance, members, opts) {
    const lines = [];
    lines.push("  - name: " + q(name));
    lines.push("    type: url-test");
    lines.push("    url: " + q(url));
    lines.push("    interval: " + interval);
    lines.push("    tolerance: " + tolerance);
    if (opts && opts.hidden) lines.push("    hidden: true");
    lines.push("    proxies:");
    for (const m of members) lines.push("      - " + q(m));
    return lines.join("\n");
}

// ── main ─────────────────────────────────────────────────────────────

export default function assembleClash(proxyYaml) {
    const names = extractNodeNames(proxyYaml);

    if (names.length === 0) {
        return header() + "proxies:\n  []\n";
    }

    // Tower's group names (no circular refs between them)
    const SELECT  = "🚀 节点选择";
    const MANUAL  = "手动切换";
    const AUTO    = "♻️ 自动选择";
    const NESTED  = "🎛️ 手动切换";
    const DIRECT  = "🎯 直连";

    // ── proxy-groups (Tower order, no circular refs) ──────────────
    const groups = [
        // 1. 🚀 节点选择 — top-level select, references other GROUPS only
        selectGroup(SELECT, [
            AUTO,
            DIRECT,
            MANUAL,
        ]),

        // 2. 手动切换 — select with all raw nodes
        selectGroup(MANUAL, names),

        // 3. ♻️ 自动选择 — url-test with all raw nodes
        urlTestGroup(AUTO, "http://www.gstatic.com/generate_204", 300, 50, names),

        // 4. 🎛️ 手动切换 — hidden nested copy (Tower's nestedManualGroupName)
        selectGroup(NESTED, names, { hidden: true }),

        // 5. 🎯 直连 — only DIRECT, never references any group
        selectGroup(DIRECT, ["DIRECT"], { hidden: true }),
    ].join("\n\n");

    // ── rules ─────────────────────────────────────────────────────
    const rules = [
        // Private / LAN
        "  - DOMAIN-SUFFIX,local," + DIRECT,
        "  - DOMAIN-SUFFIX,localhost," + DIRECT,
        "  - IP-CIDR,127.0.0.0/8," + DIRECT + ",no-resolve",
        "  - IP-CIDR,172.16.0.0/12," + DIRECT + ",no-resolve",
        "  - IP-CIDR,192.168.0.0/16," + DIRECT + ",no-resolve",
        "  - IP-CIDR,10.0.0.0/8," + DIRECT + ",no-resolve",
        // CN → direct
        "  - GEOIP,CN," + DIRECT + ",no-resolve",
        // catch-all → proxy
        "  - MATCH," + SELECT,
    ].join("\n");

    // ── assemble ──────────────────────────────────────────────────
    return header() + "\n" + proxyYaml.trimEnd() + "\n\nproxy-groups:\n" + groups + "\n\nrules:\n" + rules + "\n";
}

function header() {
    return [
        "# Generated by singbox-kit",
        "mixed-port: 7890",
        "allow-lan: false",
        "mode: rule",
        "log-level: warning",
        "ipv6: true",
        "",
        "dns:",
        "  enable: true",
        "  enhanced-mode: fake-ip",
        "  fake-ip-range: 198.18.0.1/16",
        "  fake-ip-filter:",
        '    - "*.lan"',
        '    - "+.local"',
        '    - "+.msftconnecttest.com"',
        '    - "+.msftncsi.com"',
        "  default-nameserver:",
        "    - 223.5.5.5",
        "    - 119.29.29.29",
        "  proxy-server-nameserver:",
        "    - https://223.5.5.5/dns-query",
        "  nameserver:",
        "    - https://223.5.5.5/dns-query",
        "    - https://doh.pub/dns-query",
        "  fallback:",
        "    - https://1.1.1.1/dns-query",
        "    - https://dns.google/dns-query",
        "  fallback-filter:",
        "    geoip: true",
        "    geoip-code: CN",
        "",
    ].join("\n") + "\n";
}
