// Assemble a complete clash (mihomo) config from a produced proxy YAML list.
//
// Tower generates a full config with mixed-port, dns, proxy-groups and rules.
// sub-singbox's ProxyUtils.produce only returns the proxies section; this
// module wraps it into a standalone config that clash clients can import.

import { safeLoad } from "@/utils/yaml";

// ── helpers ──────────────────────────────────────────────────────────

function extractNodeNames(proxyYaml) {
    // Try structured YAML parse first; fall back to regex for resilience.
    try {
        const doc = safeLoad(proxyYaml);
        if (doc && Array.isArray(doc.proxies)) {
            return doc.proxies
                .map((p) => p && typeof p.name === "string" ? p.name : null)
                .filter(Boolean);
        }
    } catch (_e) { /* fall through */ }

    // Regex fallback: match  - name: "value"  or  - name: value
    const names = [];
    const re = /(?:^|\n)\s*-\s*name\s*:\s*["']?([^"'\n]+?)["']?\s*(?:\n|$)/g;
    let m;
    while ((m = re.exec(proxyYaml))) {
        names.push(m[1].trim());
    }
    return names;
}

// ── main ─────────────────────────────────────────────────────────────

/**
 * assembleClash(proxyYaml, options?)
 *
 * @param {string} proxyYaml  The YAML text produced by ProxyUtils.produce
 *                             (must contain a `proxies:` section).
 * @param {object} [options]  Optional overrides.
 * @returns {string}          A complete clash YAML config.
 */
export default function assembleClash(proxyYaml, options = {}) {
    const names = extractNodeNames(proxyYaml);

    // If we couldn't extract any node names, just return the raw proxy list
    // wrapped in the bare minimum so the client at least gets the nodes.
    if (names.length === 0) {
        return (
            header() +
            "proxies:\n  []\n"
        );
    }

    // ── proxy-groups ───────────────────────────────────────────────
    const selectAll = names.map((n) => `      - "${n}"`).join("\n");
    const groups = [
        // 🚀 节点选择 — manual select with all nodes
        `  - name: "🚀 节点选择"`,
        `    type: select`,
        `    proxies:`,
        `      - "♻️ 自动选择"`,
        `      - "🎯 直连"`,
        ...names.map((n) => `      - "${n}"`),
        ``,
        // ♻️ 自动选择 — url-test with all nodes
        `  - name: "♻️ 自动选择"`,
        `    type: url-test`,
        `    url: "http://www.gstatic.com/generate_204"`,
        `    interval: 300`,
        `    tolerance: 50`,
        `    proxies:`,
        ...names.map((n) => `      - "${n}"`),
        ``,
        // 🎯 直连
        `  - name: "🎯 直连"`,
        `    type: select`,
        `    proxies:`,
        `      - DIRECT`,
        `      - "🚀 节点选择"`,
        ``,
        // 🐟 漏网之鱼
        `  - name: "🐟 漏网之鱼"`,
        `    type: select`,
        `    proxies:`,
        `      - "🚀 节点选择"`,
        `      - "♻️ 自动选择"`,
        `      - "🎯 直连"`,
    ].join("\n");

    // ── rules ──────────────────────────────────────────────────────
    const rules = [
        // Private / LAN → direct
        `  - DOMAIN-SUFFIX,local,🎯 直连`,
        `  - DOMAIN-SUFFIX,localhost,🎯 直连`,
        `  - IP-CIDR,127.0.0.0/8,🎯 直连,no-resolve`,
        `  - IP-CIDR,172.16.0.0/12,🎯 直连,no-resolve`,
        `  - IP-CIDR,192.168.0.0/16,🎯 直连,no-resolve`,
        `  - IP-CIDR,10.0.0.0/8,🎯 直连,no-resolve`,
        // CN geoip → direct
        `  - GEOIP,CN,🎯 直连`,
        // Everything else → proxy
        `  - MATCH,🐟 漏网之鱼`,
    ].join("\n");

    // ── assemble ───────────────────────────────────────────────────
    return header() + "\n" + proxyYaml.trimEnd() + "\n\nproxy-groups:\n" + groups + "\n\nrules:\n" + rules + "\n";
}

function header() {
    return [
        "# Generated by singbox-kit",
        "mixed-port: 7890",
        "allow-lan: false",
        "mode: rule",
        "log-level: warning",
        "",
        "dns:",
        "  enable: true",
        "  enhanced-mode: fake-ip",
        "  fake-ip-range: 198.18.0.1/16",
        "  fake-ip-filter:",
        '    - "*.lan"',
        '    - "+.local"',
        '    - "+.msftconnecttest.com"',
        "  default-nameserver:",
        "    - 223.5.5.5",
        "    - 119.29.29.29",
        "  nameserver:",
        "    - https://223.5.5.5/dns-query",
        "    - https://doh.pub/dns-query",
        "  fallback:",
        "    - https://1.1.1.1/dns-query",
        "    - https://dns.google/dns-query",
        "  fallback-filter:",
        "    geoip: true",
        "    geoip-code: CN",
        "",
    ].join("\n") + "\n";
}
